version: '3'

services:
  # Backend servisi (FastAPI ve Streamlit)
  backend:
    build:
      context: ./backend/app
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend/app/outputs:/app/outputs
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "8001:8000"  # FastAPI
      - "8502:8501"  # Streamlit
    command: bash -c "python3 -m uvicorn main:app --host 0.0.0.0 --port 8000 & streamlit run app.py --server.port 8501 --server.address 0.0.0.0"
    restart: unless-stopped
    networks:
      - scanfully

  # Frontend servisi (React/Vite)
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3002:5173"  # Vite geliştirme sunucusu
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:8000  # Backend'e ağ adı üzerinden erişim
    restart: unless-stopped
    networks:
      - scanfully

# Networks tanımları
networks:
  scanfully:
    driver: bridge